### ISSUE TITLE
server crashed on placing a cable next to an energy cell

### ISSUE THREAD

**Issue by MSandro** [Flytre/Mechanix#8]
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/25/21 3:02 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at team.reborn.energy.Energy.lambda$registerHolder$2(Energy.java:49)
	at team.reborn.energy.Energy.valid(Energy.java:43)
	at net.flytre.mechanix.api.energy.EnergyEntity.requestEnergy(EnergyEntity.java:395)
	at net.flytre.mechanix.block.cell.EnergyCellEntity.repeatTick(EnergyCellEntity.java:66)
	at net.flytre.mechanix.api.energy.EnergyEntity.method_16896(EnergyEntity.java:534)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at team.reborn.energy.Energy.lambda$registerHolder$2(Energy.java:49)
	at team.reborn.energy.Energy.valid(Energy.java:43)
	at net.flytre.mechanix.api.energy.EnergyEntity.requestEnergy(EnergyEntity.java:395)
	at net.flytre.mechanix.block.cell.EnergyCellEntity.repeatTick(EnergyCellEntity.java:66)
	at net.flytre.mechanix.api.energy.EnergyEntity.method_16896(EnergyEntity.java:534)

-- Block entity being ticked --
Details:
	Name: mechanix:energy_cell // net.flytre.mechanix.block.cell.EnergyCellEntity
	Block: Block{mechanix:gilded_energy_cell}[down=false,east=true,north=true,south=true,up=true,west=true]
	Block location: World: (-224,63,-1476), Chunk: (at 0,3,12 in -14,-93; contains blocks -224,0,-1488 to -209,255,-1473), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
	Block: Block{mechanix:gilded_energy_cell}[down=false,east=true,north=true,south=true,up=true,west=true]
	Block location: World: (-224,63,-1476), Chunk: (at 0,3,12 in -14,-93; contains blocks -224,0,-1488 to -209,255,-1473), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MSandro'/316, l='ServerWorld minecraft:overworld world', x=-223.99, y=61.00, z=-1476.80]]
	Chunk stats: ServerChunkCache: 3404
	Level dimension: minecraft:overworld
	Level spawn location: World: (200,74,-1300), Chunk: (at 8,4,12 in 12,-82; contains blocks 192,0,-1312 to 207,255,-1297), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 10066929 game time, 3404173 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 5409 (now: false), thunder time: 8939 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.4.0-154-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2919236280 bytes (2784 MB) / 6256590848 bytes (5966 MB) up to 6256590848 bytes (5966 MB)
	CPUs: 24
	JVM Flags: 5 total; -Xms6000M -Xmx6000M -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.2
		advdebug: Advancements Debug 2.2.0
		adventurez: AdventureZ 1.1.5
		ag4tr: Ag4tr 0.1.5.9
		allure: Allure 1.2.8
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
		aquarius: Aquarius 1.0.3
		architectury: Architectury 1.4.96
		arstheurgia: Ars Theurgia 1.0.6
		artifacts: Artifacts 2.2.1+fabric
		artifice: Artifice 0.13.2+1.16.3
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		audiooutput: AudioOutput 0.0.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.20+MC1.16.2-1.16.5
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.3.2-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		beebetter: Bee Better 1.8.0-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.8.8-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		betterslabs: Betterslabs 1.1.4
		bitsandchisels: BitsAndChisels 1.1.8
		blade: Blade 2.0.0
		blast: BLAST 1.5
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 2.0.2+1.16.4
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.3
		campanion: Campanion 1.3.2
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.6.1
		cavebiomes: Cave Biomes 0.5.1
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.2.2
		charmonium: Charmonium 2.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.2
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_nathanpb_safer: Safer 1.1.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_udojava_evalex: EvalEx 2.5
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.2
		conjuring: Conjuring 0.1.3-beta
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.1.0
		cotton-cauldron: Cotton Cauldron 1.1.0
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.3
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.1.0
		crowdin-translate: CrowdinTranslate 1.2
		crumbs: Crumbs 1.0.6
		crusade: Crusade 1.2.0
		damagetilt: Damage Tilt 1.16-fabric-0.1.1
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: Dark Paintings 2.0.0
		dawn: Dawn API 1.6.1
		daylightdimension: Daylight Dimension 0.0.2
		decimal_coins: Decimal Coins 1.16.2-1.2.0
		decorative: Decorative 3.0.0
		dehydration: Dehydration 1.0.8
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dishes: Delicious Dishes 2.0.0
		dispenser_configurator: Dispenser Configurator 1.0.1+MC1.16.4-1.16.5
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta5
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		exotic-art-core: Exotic Art Core Content Pack 1.0.379
		exotic-art-tech: Exotic Art Tech Pack 1.2.379
		exotic-matter: Exotic Matter 2.12.381
		expandedstorage: ExpandedStorage 5.6.32
		extraalchemy: Extra Alchemy 1.3.1
		extradoors: ExtraDoors 1.8.2-1.16.2
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-diagonal-panes: Fabric Diagonal Panes 0.4.0
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		facility: Facility 0.12.204
		fallflyinglib: FallFlyingLib 1.1.0
		falling_tree: FallingTree 2.10.0
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.218
		fermion-gui: Fermion GUI 2.5.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-simulator: Fermion Simulator 1.8.218
		fermion-varia: Fermion Varia 2.6.218
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		fluidity: Fluidity 0.16.204
		fluidphysics: Fluid Physics 1.3.9+fabric-1.16.4
		framed: Framed 1.0.2
		gameinfo: GameInfo 2.0.1 1.16.4
		gateofbabylon: Gate Of Babylon 1.2.1-1.16.2
		geckolib3: Geckolib 3.0.7
		givemehats: Give Me Hats! 1.4
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		goml: Get Off My Lawn 1.2.3-beta
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.0.9
		hctm-base: HCTM Base 3.5.1
		horseinfo: Horse Info 0.2.2-1.16.1
		hplus: Hopper Plus 1.0.10
		identity: Identity 1.11.4-beta-1.16.4
		ignis-fatuus: Ignis Fatuus 1.1.3
		imm_ptl_core: Immersive Portals Core 0.68
		immersive_portals: Immersive Portals 0.68
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.1.1-1.16.4
		inventorysorter: Inventory Sorter 1.7.6-1.16
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.9
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.1+j1.2.0
		jargm: Just Another Redstone Gate Mod 1.2.0
		java: OpenJDK 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.1.2
		kibe: Kibe 1.6.2-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1.5.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lakeside: Lakeside 1.0.3+1.16.4
		lamps: The Lamps! 1.1
		lapisreserve: Lapis Reserve 1.0.6
		launchersmod: Launchers 3.1.0
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		libmultipart: LibMultiPart 0.4.3
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.4.3
		libnetworkstack: Lib Network Stack 0.4.3
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.1
		magna: Magna 1.4.3-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		mechanix: Mechanix 3.3.0
		megane: megane 3.1.2+1.16.4
		megane-api: megane-api 3.1.2+1.16.4
		megane-impl: megane-impl 3.1.2+1.16.4
		megane-runtime: megane-runtime 3.1.2+1.16.4
		minecraft: Minecraft 1.16.5
		mo_glass: Mo Glass 1.5-MC1.16.5
		modern_industrialization: Modern Industrialization 0.3.9
		moreberries: More Berries 1.3.4
		moretotems: More Totems 2.7.3
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mousewheelie: Mouse Wheelie 1.6.3+mc1.16.4
		multi_item_lin: Multi Item Lin 1.0.0
		mycommands: MyCommands Fabric 1.16.1-17
		netherite_plus: Netherite Plus Mod 1.3.8-1.16.5
		nookbuild: NookBuild 1.2.1
		nourish: Nourish 1.2.0
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_joml_joml: joml 1.10.0
		oro_config: OroArmor Config -08083e902d-1
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 1.7.1+21w03a
		phonos: Phonos 0.1.1-beta
		phosphor: Phosphor 0.7.0+build.10
		piglib: Piglib 1.0.1
		plantinajar: Plant In A Jar 1.8.1
		plated: Plated 2.0.1
		platos: Plato's Transporters 1.6.4
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.7-1.16.4
		programmerartinjector: Programmer Art Injector 1.2.1
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.4+build.117
		redbits: Red Bits 1.7.0
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		respawnablepets: Respawnable Pets 1.16.5-1
		riverredux: River Redux 0.1.5
		rocks: This Rocks! 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.8.11
		roughlyenoughitems-api: REI (API) 5.8.11
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.11
		roughlyenoughitems-runtime: REI (Runtime) 5.8.11
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rswires: RSWires 4.10.1
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		sandwichable: Sandwichable 1.1.2
		secretrooms: Secret Rooms 0.9.2+1.16.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.4+1.16.4
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		simplevoidworld: Simple Void World 4.0.0
		simplexterrain: Simplex Terrain 0.7.2
		slotlink: slotlink 2.2.0+1.16.4
		smithee: Smithee 0.2.3
		smootherbedrock: Smoother Bedrock 1.0.0
		spark: spark 1.4.3
		special-circumstances: Special Circumstances 1.8.218
		stacc: Stacc 1.0.1
		staffofbuilding: Staff of Building 1.2.4-1.16.2
		statement: Statement 4.0.0+1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		supernaturalcrops: Supernatural Crops 1.0.8
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.3+build.192
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.4
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.0+build.4
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.4
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.4
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.1
		terrestria: Terrestria 2.1.6
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.2.17
		tis3d: TIS-3D 1.6.0
		tis3d-additions: TIS-3D Additions 0.2.1+1.16.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torcherino: Torcherino 2.12.69
		totemmod: Wither Totems Mod 0.3.2
		transferchestmod: Transfer Chest 1.1.3
		transparent: Transparent 2.1.0
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.1
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		tweed: Tweed API 3.0.0-beta.22
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilla_parts: Vanilla Parts 1.1.4+1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.1.1.1
		wild_explorer: Wild Explorer 1.3.1
		winged: Winged Mod 1.16.2-1.4.1
		wither_proof_block: Wither Proof Block 1.0.2
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		world_blender: World Blender 1.16.4-2.0.1
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.9
		xb: Exotic Blocks 1.6.172
		xlpackets: XLPackets 1.1
		yalbm: Yet Another Lucky BLock Mod 1.1.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Player Count: 1 / 3; [class_3222['MSandro'/316, l='ServerWorld minecraft:overworld world', x=-223.99, y=61.00, z=-1476.80]]
	Data Packs: vanilla (incompatible), Fabric Mods, global/cotton_generated, phonos:data_pack, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by MSandro** [comment]
The Enchanter and Disenchanter seems to have problems too. I placed a Energy Cable next to them and my server crashed :(

**Comment by ZenoMetal** [comment]
I've had that issue too, apparently this only happens, when the Energy Cell has defined in-/outputs. If you place the cell and then any of the tiered cables next to it without changing inout/output it kind of works, but still crashes as soon as you change them
